-- Test Challenge generated by setup_test_challenge.py
-- Compose hash: 059ce57b74502a2ccd1ac83ce77c0107cf3f5894bd6cef8bc3994a2556745c7d

INSERT INTO challenges (
    id,
    name,
    compose_hash,
    compose_yaml,
    version,
    images,
    resources,
    ports,
    env,
    emission_share,
    mechanism_id,
    weight,
    description,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'test-challenge',
    '059ce57b74502a2ccd1ac83ce77c0107cf3f5894bd6cef8bc3994a2556745c7d',
    'dmVyc2lvbjogJzMuOCcKCnNlcnZpY2VzOgogIHRlc3QtY2hhbGxlbmdlOgogICAgaW1hZ2U6IHB5dGhvbjozLjExLXNsaW0KICAgIGNvbnRhaW5lcl9uYW1lOiB0ZXN0LWNoYWxsZW5nZQogICAgcmVzdGFydDogdW5sZXNzLXN0b3BwZWQKICAgIHdvcmtpbmdfZGlyOiAvYXBwCiAgICB2b2x1bWVzOgogICAgICAtIC4uL3NyYzovYXBwL3BsYXRmb3JtX2NoYWxsZW5nZV9zZGs6cm8KICAgICAgLSAuL3Rlc3RfY2hhbGxlbmdlLnB5Oi9hcHAvbWFpbi5weTpybwogICAgY29tbWFuZDogcHl0aG9uIG1haW4ucHkKICAgIGVudmlyb25tZW50OgogICAgICAtIFJVU1RfTE9HPWluZm8KICAgICAgLSBWQUxJREFUT1JfQkFTRV9VUkw9aHR0cDovL2xvY2FsaG9zdDo4MDgwCiAgICBwb3J0czoKICAgICAgLSAiMTAwMDA6MTAwMDAiCiAgICBoZWFsdGhjaGVjazoKICAgICAgdGVzdDogWyJDTUQiLCAiY3VybCIsICItZiIsICJodHRwOi8vbG9jYWxob3N0OjEwMDAwL2hlYWx0aCJdCiAgICAgIGludGVydmFsOiAxMHMKICAgICAgdGltZW91dDogNXMKICAgICAgcmV0cmllczogMwogICAgICBzdGFydF9wZXJpb2Q6IDEwcwoK',
    '1.0.0',
    ARRAY['python:3.11-slim'],
    '{"vcpu": 2, "memory": "2G", "disk": "10G"}'::jsonb,
    '[{"container": 10000, "protocol": "tcp"}]'::jsonb,
    '{}'::jsonb,
    0.1,
    'default',
    1.0,
    'Simple test challenge for validating the platform',
    NOW(),
    NOW()
)
ON CONFLICT (compose_hash) DO UPDATE SET
    updated_at = NOW(),
    version = EXCLUDED.version,
    compose_yaml = EXCLUDED.compose_yaml;
